// Write src/lib/ui/emojidata.gen.ts from the Emojibase data. Run it with Node 22 or newer
// after the emojibase-data package changes: node scripts/gen-emoji.mjs
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { compactEmoji } from '../src/lib/ui/emojibuild.ts';

const require = createRequire(import.meta.url);
const data = require('emojibase-data/en/data.json');
const text = compactEmoji(data);
const header =
  '// Generated by scripts/gen-emoji.mjs from Emojibase 17 (MIT). Do not edit by hand.\n' +
  '// The format is in emojibuild.ts.\n';
const out = new URL('../src/lib/ui/emojidata.gen.ts', import.meta.url);
writeFileSync(out, `${header}export default ${JSON.stringify(text)};\n`);
console.log(`wrote ${out.pathname}: ${(text.length / 1024).toFixed(0)} KB`);
